### ISSUE TITLE
cargo build --release

### ISSUE THREAD

**Issue by zanjs** [rust-cn/rust_lang_cn#7]
```
➜  rust_lang_cn cargo build --release
   Compiling kernel32-sys v0.2.1
   Compiling toml v0.1.28
   Compiling conduit-mime-types v0.7.3
   Compiling unicode-bidi v0.2.3
   Compiling num v0.1.31
   Compiling uuid v0.1.18
   Compiling unicase v1.4.0
   Compiling openssl-sys-extras v0.7.9
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys-extras v0.7.9`
Process didn't exit successfully: `/Users/julaud/www/rust/rust_lang_cn/target/release/build/openssl-sys-extras-358c9a6ad3e03664/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("x86_64-apple-darwin")
debug=false opt-level=3
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-o" "/Users/julaud/www/rust/rust_lang_cn/target/release/build/openssl-sys-extras-358c9a6ad3e03664/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
src/openssl_shim.c:1:10: fatal error: 'openssl/hmac.h' file not found
#include <openssl/hmac.h>
         ^
1 error generated.
thread '<main>' panicked at 'explicit panic', /Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/gcc-0.3.26/src/lib.rs:818
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by MiYogurt** [comment]
刚开始可能是没有找到系统里面一些关于openssl的编译依赖。

试一试这个，我这样之后就可以编译正常了。

```
brew install openssl
brew link openssl --force
```

**Comment by zanjs** [comment]
不知道为何 还是没用 是  openssl 版本问题吗

```
➜  ~ brew install openssl
Warning: openssl-1.0.2h_1 already installed
➜  ~ brew link openssl --force
Linking /usr/local/Cellar/openssl/1.0.2h_1... 1601 symlinks created
➜  ~ cd /Users/julaud/www/rust/rust_lang_cn 
➜  rust_lang_cn code ./
➜  rust_lang_cn cargo build --release
   Compiling rust-crypto v0.2.35
   Compiling openssl v0.7.9
   Compiling serde_json v0.7.0
   Compiling ordered-float v0.1.0
   Compiling openssl-sys-extras v0.7.9
   Compiling kernel32-sys v0.2.1
   Compiling url v0.2.38
   Compiling string_cache v0.2.16
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl v0.7.9`
```

**Comment by liyuan462** [comment]
运行下列命令试试

```
cargo clean
export DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include
export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib
cargo build
```

**Comment by zanjs** [comment]
遇到这样的错误 🙅

```
<grabbag_macros macros>:8:73: 8:76 warning: `$inits:expr` may be followed by `...`, which is not allowed for `expr` fragments
<grabbag_macros macros>:8 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
```

具体内容如下

```
➜  rust_lang_cn cargo clean
➜  rust_lang_cn export DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include
➜  rust_lang_cn export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
➜  rust_lang_cn export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib
➜  rust_lang_cn cargo build
   Compiling bitflags v0.4.0
   Compiling itertools v0.4.12
   Compiling phf_shared v0.7.14
   Compiling utf8-ranges v0.1.3
   Compiling mempool v0.3.1
   Compiling yaml-rust v0.3.2
   Compiling lazy_static v0.2.1
   Compiling typeable v0.1.2
   Compiling pkg-config v0.3.8
   Compiling cfg-if v0.1.0
   Compiling modifier v0.1.0
   Compiling serde v0.7.0
   Compiling grabbag_macros v0.1.0
   Compiling matches v0.1.2
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:179:61: 179:64 warning: `$inits:expr` may be followed by `...`, which is not allowed for `expr` fragments
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:179     ( $seq:ident [ $ind:ident ]: $sty:ty = $($inits:expr),+ ... $closed_form:expr ) => {
                                                                                                                                                              ^~~
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:179:61: 179:64 note: The above warning will be a hard error in the next release.
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:179     ( $seq:ident [ $ind:ident ]: $sty:ty = $($inits:expr),+ ... $closed_form:expr ) => {
                                                                                                                                                              ^~~
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:236:61: 236:64 warning: `$inits:expr` may be followed by `...`, which is not allowed for `expr` fragments
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:236     ( $seq:ident [ $ind:ident ]: $sty:ty = $($inits:expr),+ ... $recur:expr ) => {
                                                                                                                                                              ^~~
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:236:61: 236:64 note: The above warning will be a hard error in the next release.
/Users/julaud/.cargo/registry/src/github.com-88ac128001ac3a9a/grabbag_macros-0.1.0/src/lib.rs:236     ( $seq:ident [ $ind:ident ]: $sty:ty = $($inits:expr),+ ... $recur:expr ) => {
                                                                                                                                                              ^~~
   Compiling unicode-bidi v0.2.3
   Compiling rc v0.1.1
   Compiling byteorder v0.4.2
   Compiling phf v0.7.14
   Compiling quick-error v0.1.4
   Compiling traitobject v0.0.1
   Compiling unsafe-any v0.4.1
   Compiling error v0.1.9
   Compiling typemap v0.3.3
   Compiling bitflags v0.5.0
   Compiling libc v0.2.8
   Compiling openssl-sys v0.7.9
   Compiling crossbeam v0.2.9
   Compiling libc v0.1.12
   Compiling winapi v0.2.6
   Compiling gcc v0.3.26
   Compiling traitobject v0.0.3
   Compiling semver v0.1.20
   Compiling log v0.3.5
   Compiling memchr v0.1.11
   Compiling num_cpus v0.2.11
   Compiling unix_socket v0.5.0
   Compiling antidote v0.1.0
   Compiling rustc-serialize v0.3.18
   Compiling httparse v1.1.1
   Compiling rust-crypto v0.2.35
   Compiling aho-corasick v0.5.1
   Compiling rustc_version v0.1.7
   Compiling openssl-sys-extras v0.7.9
   Compiling openssl v0.7.9
   Compiling plugin v0.2.6
   Compiling lazy_static v0.1.15
   Compiling void v1.0.2
   Compiling unreachable v0.1.1
   Compiling unicase v1.4.0
   Compiling winapi-build v0.1.1
   Compiling debug_unreachable v0.1.1
   Compiling mac v0.0.2
   Compiling futf v0.1.2
   Compiling regex-syntax v0.3.1
   Compiling fnv v1.0.2
   Compiling kernel32-sys v0.2.1
   Compiling getopts v0.2.14
   Compiling mime v0.2.0
   Compiling route-recognizer v0.1.11
   Compiling hpack v0.2.0
   Compiling encoding_index_tests v0.1.4
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling pulldown-cmark v0.0.8
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling unicode-normalization v0.1.2
   Compiling language-tags v0.2.2
   Compiling solicit v0.4.4
   Compiling encoding-index-japanese v1.20141219.5
   Compiling bufstream v0.1.1
   Compiling time v0.1.34
   Compiling regex v0.1.65
   Compiling walkdir v0.1.5
   Compiling rand v0.3.14
   Compiling encoding v0.2.32
   Compiling serde_yaml v0.2.4
   Compiling phf_generator v0.7.14
   Compiling phf_codegen v0.7.14
   Compiling string_cache v0.2.16
   Compiling tendril v0.1.6
   Compiling conduit-mime-types v0.7.3
   Compiling num v0.1.31
   Compiling toml v0.1.28
   Compiling uuid v0.1.18
   Compiling html5ever v0.2.11
   Compiling url v0.5.7
   Compiling url v0.2.38
   Compiling cookie v0.2.2
   Compiling serde_json v0.7.0
   Compiling ordered-float v0.1.0
   Compiling handlebars v0.16.0
   Compiling chrono v0.2.22
   Compiling serde-value v0.2.1
   Compiling hyper v0.8.0
   Compiling mysql v3.0.0
   Compiling log4rs v0.4.3
   Compiling ammonia v0.1.1
<grabbag_macros macros>:8:73: 8:76 warning: `$inits:expr` may be followed by `...`, which is not allowed for `expr` fragments
<grabbag_macros macros>:8 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
<grabbag_macros macros>:8:73: 8:76 note: The above warning will be a hard error in the next release.
<grabbag_macros macros>:8 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
<grabbag_macros macros>:2:73: 2:76 warning: `$inits:expr` may be followed by `...`, which is not allowed for `expr` fragments
<grabbag_macros macros>:2 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
<grabbag_macros macros>:2:73: 2:76 note: The above warning will be a hard error in the next release.
<grabbag_macros macros>:2 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
   Compiling iron v0.3.0
   Compiling persistent v0.1.0
   Compiling router v0.1.1
   Compiling oven v0.3.0
   Compiling handlebars-iron v0.15.0
   Compiling bodyparser v0.3.0
   Compiling iron-login v0.4.1
   Compiling urlencoded v0.3.0
   Compiling rust_lang_cn v0.1.0 (file:///Users/julaud/www/rust/rust_lang_cn)
<grabbag_macros macros>:8:73: 8:76 warning: `$inits:expr` may be followed by `...`, which is not allowed for `expr` fragments
<grabbag_macros macros>:8 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
<grabbag_macros macros>:8:73: 8:76 note: The above warning will be a hard error in the next release.
<grabbag_macros macros>:8 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
<grabbag_macros macros>:2:73: 2:76 warning: `$inits:expr` may be followed by `...`, which is not allowed for `expr` fragments
<grabbag_macros macros>:2 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
<grabbag_macros macros>:2:73: 2:76 note: The above warning will be a hard error in the next release.
<grabbag_macros macros>:2 $ seq : ident [ $ ind : ident ] : $ sty : ty = $ ( $ inits : expr ) , + ... $
                                                                                                  ^~~
➜  rust_lang_cn 

```

**Comment by liyuan462** [comment]
warning可以暂时先忽略，应该不影响编译。后面考虑移除这个依赖。

最新修改：已经移除了grabbag_macros依赖.

**Comment by liyuan462** [comment]
@zanjs 怎么样，运行起来了吗？

**Comment by zanjs** [comment]
@liyuan462
好像还是有错误 ，按照您的 readme 步骤安装的,还少什么吗
➜  rust_lang_cn ./target/release/rust_lang_cn
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Log4rs(Error { repr: Os { code: 2, message: "No such file or directory" } })', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by liyuan462** [comment]
@zanjs 
拷贝config-sample.toml至config.toml，修改其中的数据库配置
拷贝log4rs-sample.yaml至log4rs.yaml，可以不用修改

README中有个笔误

是不是没有log4rs.yaml？

**Comment by zanjs** [comment]
@liyuan462  终于 可以了  笔误 感谢 细心知道 ，终于入坑了
